import json

from rich.console import Console
from rich.table import Table

from repopulse.models import ComparisonReport, HealthReport


def _score_percent(report: HealthReport) -> int:
    if report.max_score <= 0:
        return 0
    return round((report.total_score / report.max_score) * 100)


def render_markdown(report: HealthReport) -> str:
    """Render a maintainer-friendly Markdown health report."""
    repo = report.repository
    private = "Yes" if repo.private else "No"
    updated = repo.last_pushed_at or "Unknown"
    percent = _score_percent(report)
    failed = [c for c in report.checks if c.status == "fail"]
    warned = [c for c in report.checks if c.status == "warn"]
    passed = [c for c in report.checks if c.status == "pass"]

    lines = [
        "# RepoPulse Health Report",
        "",
        f"> Generated by RepoPulse · schema `{report.schema_version}` · grade {report.grade}",
        "",
        "## Repository",
        f"- **Name:** {repo.full_name}",
        f"- **URL:** {repo.url}",
        f"- **Default branch:** {repo.default_branch}",
        f"- **Private:** {private}",
        f"- **Stars:** {repo.stars}",
        f"- **Forks:** {repo.forks}",
        f"- **Open issues:** {repo.open_issues}",
        f"- **Last updated:** {updated}",
        "",
        "## Final Score",
        f"**{report.total_score} / {report.max_score} ({percent}%) - {report.grade}**",
        "",
        "| Pass | Warn | Fail |",
        "|---:|---:|---:|",
        f"| {len(passed)} | {len(warned)} | {len(failed)} |",
        "",
        "## Checks",
        "| Check | Status | Score | Notes |",
        "|---|---|---:|---|",
    ]
    for check in report.checks:
        lines.append(
            f"| {check.title} | {check.status.title()} | {check.score}/{check.max_score} | {check.message} |"
        )

    if failed or warned:
        lines.extend(["", "## Attention needed"])
        for check in failed + warned:
            lines.append(f"### {check.title} (`{check.status}`)")
            lines.append(f"{check.message}")
            if check.recommendations:
                lines.append("")
                lines.append("**Next steps:**")
                lines.extend(f"- {item}" for item in check.recommendations)
            lines.append("")

    lines.extend(["## Recommendations"])
    if report.recommendations:
        lines.extend(
            f"{index}. {recommendation}"
            for index, recommendation in enumerate(report.recommendations, start=1)
        )
    else:
        lines.append("No high-priority recommendations.")
    lines.append("")

    if report.config:
        lines.extend(
            [
                "## Applied config",
                "```json",
                json.dumps(report.config, indent=2, ensure_ascii=False),
                "```",
                "",
            ]
        )

    lines.extend(
        [
            "---",
            "*Tip: use `--format issues` for paste-ready GitHub issue bodies.*",
            "",
        ]
    )
    return "\n".join(lines)


def render_json(report: HealthReport) -> str:
    """Stable machine-readable JSON (`schema_version` is part of the contract)."""
    return json.dumps(report.model_dump(), indent=2, ensure_ascii=False, sort_keys=True)


def render_summary(report: HealthReport) -> str:
    lines = [
        f"{report.repository.full_name}: {report.total_score} / {report.max_score} - {report.grade}",
    ]
    if report.recommendations:
        lines.append("Top recommendations:")
        lines.extend(f"- {recommendation}" for recommendation in report.recommendations[:3])
    return "\n".join(lines)


def render_issues(report: HealthReport) -> str:
    """Render GitHub-issue-ready Markdown blocks for fail/warn checks and any with recommendations."""
    repo = report.repository
    full_name = repo.full_name
    lines = [
        f"# RepoPulse recommendations for {full_name}",
        f"Score: {report.total_score}/{report.max_score} — {report.grade}",
        "",
    ]

    actionable = [
        check
        for check in report.checks
        if check.status in {"fail", "warn"} or check.recommendations
    ]

    if not actionable:
        lines.append(
            f"No open recommendations from RepoPulse for {full_name} "
            f"(score {report.total_score}/{report.max_score} — {report.grade})."
        )
        return "\n".join(lines)

    blocks: list[str] = []
    for check in actionable:
        block_lines = [
            f"## [RepoPulse] {check.title}: {check.status}",
            "",
            f"**Repository:** {full_name}",
            f"**Score impact:** {check.score}/{check.max_score}",
            f"**Summary:** {check.message}",
            "",
            "### Action items",
        ]
        if check.recommendations:
            block_lines.extend(f"- {item}" for item in check.recommendations)
        else:
            block_lines.append("- Review this check and improve the repository.")
        block_lines.extend(
            [
                "",
                "### Labels",
                f"`repopulse`, `health-check`, `{check.key}`",
            ]
        )
        blocks.append("\n".join(block_lines))

    lines.append("\n\n---\n\n".join(blocks))
    lines.append("")
    return "\n".join(lines)


def render_terminal(report: HealthReport, console: Console | None = None, verbose: bool = False) -> None:
    target = console or Console()
    repo = report.repository
    target.print(f"[bold]RepoPulse Health Report[/bold] for [cyan]{repo.full_name}[/cyan]")
    target.print(f"Score: [bold]{report.total_score} / {report.max_score}[/bold] - {report.grade}")
    target.print(
        f"Default branch: {repo.default_branch} | Stars: {repo.stars} | "
        f"Forks: {repo.forks} | Open issues: {repo.open_issues}"
    )

    table = Table(title="Checks")
    table.add_column("Check")
    table.add_column("Status")
    table.add_column("Score", justify="right")
    table.add_column("Notes")
    for check in report.checks:
        style = "green" if check.status == "pass" else "yellow" if check.status == "warn" else "red"
        table.add_row(
            check.title,
            f"[{style}]{check.status.upper()}[/{style}]",
            f"{check.score}/{check.max_score}",
            check.message,
        )
    target.print(table)

    recommendations = report.recommendations if verbose else report.recommendations[:3]
    if recommendations:
        target.print("[bold]Recommendations[/bold]")
        for index, recommendation in enumerate(recommendations, start=1):
            target.print(f"{index}. {recommendation}")
        if not verbose and len(report.recommendations) > 3:
            target.print(f"...and {len(report.recommendations) - 3} more. Use --verbose to show all.")


def _delta_sign(value: int) -> str:
    if value > 0:
        return f"+{value}"
    return str(value)


def render_comparison_markdown(comparison: ComparisonReport) -> str:
    """Maintainer-friendly Markdown comparison of two scans."""
    lines = [
        "# RepoPulse Comparison Report",
        "",
        f"> schema `{comparison.schema_version}` · baseline **{comparison.baseline_label}** → target **{comparison.target_label}**",
        "",
        "## Score",
        "| | Baseline | Target | Delta |",
        "|---|---:|---:|---:|",
        (
            f"| Score | {comparison.baseline_score}/{comparison.baseline_max_score} "
            f"| {comparison.target_score}/{comparison.target_max_score} "
            f"| {_delta_sign(comparison.score_delta)} |"
        ),
        (
            f"| Grade | {comparison.baseline_grade} | {comparison.target_grade} | |"
        ),
        "",
        f"- **Improved:** {len(comparison.improved)}"
        + (f" (`{', '.join(comparison.improved)}`)" if comparison.improved else " (—)"),
        f"- **Regressed:** {len(comparison.regressed)}"
        + (f" (`{', '.join(comparison.regressed)}`)" if comparison.regressed else " (—)"),
        f"- **Unchanged:** {len(comparison.unchanged)}",
        "",
        "## Checks",
        "| Check | Baseline | Target | Score Δ | Change |",
        "|---|---|---|---:|---|",
    ]
    for check in comparison.checks:
        base = f"{check.baseline_status or '—'} ({check.baseline_score if check.baseline_score is not None else '—'})"
        tgt = f"{check.target_status or '—'} ({check.target_score if check.target_score is not None else '—'})"
        lines.append(
            f"| {check.title} (`{check.key}`) | {base} | {tgt} | {_delta_sign(check.score_delta)} | {check.change} |"
        )
    lines.append("")
    if comparison.regressed:
        lines.extend(["## Regressions", ""])
        for key in comparison.regressed:
            match = next((c for c in comparison.checks if c.key == key), None)
            if match:
                lines.append(
                    f"- **{match.title}** (`{key}`): "
                    f"{match.baseline_status or '—'} → {match.target_status or '—'} "
                    f"({_delta_sign(match.score_delta)})"
                )
        lines.append("")
    return "\n".join(lines)


def render_comparison_json(comparison: ComparisonReport) -> str:
    return json.dumps(comparison.model_dump(), indent=2, ensure_ascii=False, sort_keys=True)


def render_comparison_summary(comparison: ComparisonReport) -> str:
    direction = "up" if comparison.score_delta > 0 else "down" if comparison.score_delta < 0 else "flat"
    lines = [
        (
            f"{comparison.baseline_label} → {comparison.target_label}: "
            f"{comparison.baseline_score} → {comparison.target_score} "
            f"({_delta_sign(comparison.score_delta)}, {direction})"
        ),
        f"Improved: {len(comparison.improved)} | Regressed: {len(comparison.regressed)} | Unchanged: {len(comparison.unchanged)}",
    ]
    if comparison.regressed:
        lines.append("Regressions: " + ", ".join(comparison.regressed))
    if comparison.improved:
        lines.append("Improvements: " + ", ".join(comparison.improved))
    return "\n".join(lines)


def render_comparison_terminal(comparison: ComparisonReport, console: Console | None = None) -> None:
    target = console or Console()
    delta_style = "green" if comparison.score_delta > 0 else "red" if comparison.score_delta < 0 else "white"
    target.print(
        f"[bold]RepoPulse Comparison[/bold]: "
        f"[cyan]{comparison.baseline_label}[/cyan] → [cyan]{comparison.target_label}[/cyan]"
    )
    target.print(
        f"Score: {comparison.baseline_score}/{comparison.baseline_max_score} "
        f"→ {comparison.target_score}/{comparison.target_max_score} "
        f"([{delta_style}]{_delta_sign(comparison.score_delta)}[/{delta_style}]) "
        f"| {comparison.baseline_grade} → {comparison.target_grade}"
    )
    target.print(
        f"Improved: [green]{len(comparison.improved)}[/green] | "
        f"Regressed: [red]{len(comparison.regressed)}[/red] | "
        f"Unchanged: {len(comparison.unchanged)}"
    )

    table = Table(title="Check deltas")
    table.add_column("Check")
    table.add_column("Baseline")
    table.add_column("Target")
    table.add_column("Δ", justify="right")
    table.add_column("Change")
    for check in comparison.checks:
        change_style = {
            "improved": "green",
            "regressed": "red",
            "added": "cyan",
            "removed": "yellow",
            "unchanged": "dim",
        }.get(check.change, "white")
        base = f"{check.baseline_status or '—'} ({check.baseline_score if check.baseline_score is not None else '—'})"
        tgt = f"{check.target_status or '—'} ({check.target_score if check.target_score is not None else '—'})"
        table.add_row(
            check.title,
            base,
            tgt,
            _delta_sign(check.score_delta),
            f"[{change_style}]{check.change}[/{change_style}]",
        )
    target.print(table)
